noteu/noteu

- README.md
- src/main/java/com/noteu/noteu/subject/service/impl/SubjectMemberServiceImpl.java
- src/main/java/com/noteu/noteu/subject/service/impl/SubjectServiceImpl.java
SubjectService interface 를 만들어 놓고 구현하지 않아 스타트 오류가 있어 수정
- #4 
this closes #4
> service 인터페이스 구현 추가

- src/main/resources/templates/layout/test.html
> fix: test.html

- src/main/resources/data.sql
> Member 데이터 추가

- src/main/resources/templates/fragments/common/sidebar1.html
- src/main/resources/templates/fragments/common/sidebar2.html
- src/main/resources/templates/fragments/common/topbar.html
- src/main/resources/templates/fragments/content/subject/add_content.html
- src/main/resources/templates/fragments/content/subject/list_content.html
- src/main/resources/templates/layout/subject/add.html
- src/main/resources/templates/layout/subject/list.html
> update: add_content.html

- src/main/resources/templates/fragments/common/header.html
- src/main/resources/templates/layout/test.html
/templates/fragments/common/header.html
/templates/layout/test.html
test.html에 레이아웃 사용 예시 작성 해 놨습니다. 참고하세요!
> update : layout header 변경 #17 

- src/main/resources/templates/fragments/common/header.html
- src/main/resources/templates/fragments/common/script.html
- src/main/resources/templates/layout/test.html
Layout 수정 #17 
-----
/templates/fragments/common/header.html
/templates/fragments/common/script.html
/templates/layout/test.html
> #17 update : Layout 수정

- src/main/java/com/noteu/noteu/member/controller/MemberController.java
- src/main/java/com/noteu/noteu/member/dto/MemberInfo.java
- src/main/java/com/noteu/noteu/member/security/filter/JwtAuthenticationFilter.java
- src/main/java/com/noteu/noteu/member/security/filter/JwtVerificationFilter.java
- src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationEntryPoint.java
- src/main/java/com/noteu/noteu/member/security/handler/MemberAuthenticationSuccessHandler.java
- src/main/resources/templates/fragments/member/sign_in.html
> #28 feat: 로그인 시 쿠키 생성, 토큰 값 담기

- src/main/java/com/noteu/noteu/member/security/filter/JwtAuthenticationFilter.java
> #30 fix: 쿠키 설정 추가

- src/main/resources/templates/fragments/member/sign_in.html
> #30 fix: 로그인 후 과목 목록으로 이동

- src/main/resources/templates/fragments/member/sign_in.html
> #33 fix: 로그인 후 principal 객체 null 오류 수정

- src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
- src/main/resources/templates/fragments/common/sidebar2.html
> #49 refactor: 사이드바 수정

- src/main/resources/static/js/task/detail.js
학생으로 로그인 시, div_edit, div_delete가 html에 존재하지 않아서 js 코드가 작동하지 않음. 그래서 div_edit과 div_delete 이벤트 리스너는 맨 밑으로 이동.
> fix: /task/detail.js

- src/main/java/com/noteu/noteu/member/controller/MemberController.java
- src/main/java/com/noteu/noteu/member/dto/MemberPasswordDto.java
- src/main/java/com/noteu/noteu/member/entity/Member.java
- src/main/java/com/noteu/noteu/member/service/MemberDetailsService.java
- src/main/java/com/noteu/noteu/member/service/UserDetailsManager.java
- src/main/resources/templates/fragments/content/member/change_password.html
- src/main/resources/templates/layout/member/change_password.html
> #54 feat: 비밀번호 변경

- src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
- src/main/java/com/noteu/noteu/reference/converter/ReferenceRoomConverter.java
- src/main/java/com/noteu/noteu/reference/service/impl/ReferenceRoomServiceImpl.java
- src/main/resources/static/js/reference/add-submit.js
- src/main/resources/static/js/reference/list.js
- src/main/resources/templates/fragments/content/reference/add-form.html
- src/main/resources/templates/fragments/content/reference/list.html
- 자료실 뷰 페이지 이동 url에 {subjectId} 하드코딩 부분 수정
- #67 
- this closes #67
> #67 refactor: 자료실 뷰 페이지 이동 경로 수정

- .gitignore
- build.gradle
- src/main/java/com/noteu/noteu/common/CommonUtil.java
- src/main/java/com/noteu/noteu/question/controller/QuestionPostController.java
- src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
- src/main/java/com/noteu/noteu/question/converter/impl/QuestionPostConverterImpl.java
- src/main/java/com/noteu/noteu/question/dto/QuestionCommentDTO.java
- src/main/java/com/noteu/noteu/question/dto/QuestionPostDTO.java
- src/main/java/com/noteu/noteu/question/dto/request/AddRequestQuestionPostDTO.java
- src/main/java/com/noteu/noteu/question/dto/response/DetailResponseQuestionPostDTO.java
- src/main/java/com/noteu/noteu/question/dto/response/GetAllResponseQuestionPostDTO.java
- src/main/java/com/noteu/noteu/question/entity/QuestionComment.java
- src/main/java/com/noteu/noteu/question/entity/QuestionPost.java
- src/main/java/com/noteu/noteu/question/repository/QuestionCommentRepository.java
- src/main/java/com/noteu/noteu/question/service/QuestionPostService.java
- src/main/java/com/noteu/noteu/question/service/impl/QuestionPostServiceImpl.java
- src/main/resources/static/js/question/add-submit.js
- src/main/resources/static/js/question/detail.js
- src/main/resources/static/js/question/list.js
- src/main/resources/templates/fragments/content/question/add-form.html
- src/main/resources/templates/fragments/content/question/detail.html
- src/main/resources/templates/fragments/content/question/list.html
- src/main/resources/templates/layout/question/add.html
- src/main/resources/templates/layout/question/detail.html
- src/main/resources/templates/layout/question/list.html
> #50 feat: 질문게시판 작성 / 조회 기능 추가

- src/main/java/com/noteu/noteu/question/controller/QuestionPostController.java
- src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
- src/main/java/com/noteu/noteu/question/dto/request/RequestQuestionPostDTO.java
- src/main/java/com/noteu/noteu/question/entity/QuestionPost.java
- src/main/java/com/noteu/noteu/question/service/QuestionPostService.java
- src/main/java/com/noteu/noteu/question/service/impl/QuestionPostServiceImpl.java
- src/main/resources/static/js/question/edit-submit.js
- src/main/resources/templates/fragments/content/question/detail.html
- src/main/resources/templates/fragments/content/question/edit-form.html
- src/main/resources/templates/layout/question/detail.html
- src/main/resources/templates/layout/question/edit.html
- src/main/resources/templates/layout/question/list.html
> #50 질문게시판 수정 / 삭제 기능 추가

- src/main/java/com/noteu/noteu/question/controller/QuestionCommentController.java
- src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
- src/main/java/com/noteu/noteu/question/dto/request/RequestQuestionCommentDTO.java
- src/main/java/com/noteu/noteu/question/dto/response/DetailResponseQuestionPostDTO.java
- src/main/java/com/noteu/noteu/question/dto/response/ResponseQuestionCommentDTO.java
- src/main/java/com/noteu/noteu/question/entity/QuestionComment.java
- src/main/java/com/noteu/noteu/question/service/QuestionCommentService.java
- src/main/java/com/noteu/noteu/question/service/impl/QuestionCommentServiceImpl.java
- src/main/resources/static/js/question/add-submit.js
- src/main/resources/static/js/question/detail.js
- src/main/resources/static/js/question/edit-submit.js
- src/main/resources/templates/fragments/content/question/detail.html
> #75 질문게시판 댓글 작성 / 게시글과 조회 / 삭제 기능 추가

- src/main/java/com/noteu/noteu/reference/controller/ReferenceRoomController.java
- src/main/java/com/noteu/noteu/reference/repository/ReferenceRoomRepository.java
- src/main/java/com/noteu/noteu/reference/service/ReferenceRoomService.java
- src/main/java/com/noteu/noteu/reference/service/impl/ReferenceRoomServiceImpl.java
- src/main/resources/static/js/reference/list.js
- src/main/resources/templates/fragments/content/reference/detail.html
- src/main/resources/templates/fragments/content/reference/edit-form.html
- src/main/resources/templates/fragments/content/reference/list.html
- src/main/resources/templates/layout/reference/list.html
> 자료실 제목으로 검색 기능 추가

- .gitignore
- build.gradle
- src/main/java/com/noteu/noteu/chat/controller/ChatRoomController.java
- src/main/java/com/noteu/noteu/chat/converter/ChatConverter.java
- src/main/java/com/noteu/noteu/member/dto/response/MemberResponseDto.java
- src/main/java/com/noteu/noteu/sse/SseController.java
- src/main/java/com/noteu/noteu/sse/SseEmitterService.java
- src/main/java/com/noteu/noteu/sse/dto/SseNewChatDto.java
- src/main/resources/static/js/chat/chat.js
- src/main/resources/static/js/sse/sse.js
- src/main/resources/templates/layout/chat/chat.html
- SSE 기반 실시간 응답 대기 구현
- 유저 아이디로 표시되던 채팅 이름을 유저 이름으로 변경
- #81 
this closes #81
> 실시간 응답 대기 구현

- src/main/resources/static/js/question/detail.js
- 댓글 id / 댓글 삭제 버튼 id 속성을 class로 수정
- #91 
- this closes #91
> 댓글 id / 댓글 삭제 버튼 수정

- src/main/java/com/noteu/noteu/chat/repository/querydsl/impl/ChatRoomRepositoryCustomImpl.java
- src/main/java/com/noteu/noteu/chat/service/impl/RestChatServiceImpl.java
- src/main/resources/static/js/chat/chat.js
- #93 
Join 쿼리를 사용해 메시지가 없으면 방을 못 불러왔습니다.
현재 로직은 Sse를 사용해 빈방을 먼저 만들어주고 소켓연결을 통해 상대 메시지를 받습니다.
Join -> leftJoin으로 변경해 메시지가 없어도 방을 불러 올 수 있게 되었습니다. 
this closes #93
> #93 bug : 채팅방을 못 불러오는 버그 수정

- src/main/resources/templates/layout/error/pages-404.html
- src/main/resources/templates/layout/error/pages-500.html
- src/main/resources/templates/layout/error/pages-maintenance.html
- 템플릿 기본 로고에서 noteu로고로 변경
- #112 
- Close #112
> 에러 페이지 로고 변경

- src/main/resources/templates/fragments/content/question/detail.html
- 질문게시글 상세 페이지 프로필 사진 크기 / 작성자 명 위치 수정
- #114 
- Close #114
> 질문게시글 프로필 사진 크기 및 작성자 명 위치 수정

- src/main/resources/templates/index.html
- 메인 페이지 위치 중앙으로 변경
- #115 
- Close #115
> 홈 페이지 위치 속성 추가

- src/main/resources/static/js/chat/chat.js
- #120 
표시 선택 수정
this closes #120
> #120 refactor : 채팅 선택표시 수정

- src/main/java/com/noteu/noteu/question/converter/QuestionPostConverter.java
- src/main/java/com/noteu/noteu/question/dto/response/ResponseQuestionCommentDTO.java
- src/main/resources/static/js/question/detail.js
- src/main/resources/templates/fragments/content/question/detail.html
- ResponseQuestionCommentDTO에 memberRole 추가
- memberRole이 선생님인 경우 댓글 작성 시 "Teacher" badge와 함께 이름 출력
- #125 
- Close #125
> 질문게시판 댓글 작성자 badge 표시

- src/main/resources/templates/fragments/common/header.html
- header.html에 favicon 이미지 등록
- #126 
- Close #126
> favicon 등록

- src/main/resources/static/js/index/index.js
- src/main/resources/templates/index.html
> #122 feat : 버튼 카운트

- src/main/java/com/noteu/noteu/config/fileConfig.java
> 프로필 사진 경로 설정

- src/main/resources/templates/layout/error/pages-404.html
- src/main/resources/templates/layout/error/pages-500.html
- src/main/resources/templates/layout/error/pages-maintenance.html
- 에러페이지 favicon 등록
- #139 
- Close #139
> 에러페이지 favicon 등록

- src/main/resources/static/js/index/index.js
- src/main/resources/templates/index.html
> 홈페이지 디자인, click event

- src/main/java/com/noteu/noteu/member/controller/MemberController.java
- src/main/resources/templates/index.html
- 탈퇴 후 로그아웃 페이지를 요청하여 로그아웃 처리까지
> 회원 탈퇴 후 로그아웃

- README.md
> README 작성

- README.md
> README 배포 URL 수정
